[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
members = [
	"crates/sweet_core",
	"crates/sweet_render",
	"crates/sweet_rsx",
	"crates/sweet_rsx/macros",
	"crates/sweet_server",
	"crates/sweet_site",
	"crates/sweet_test/macros",
	"crates/sweet_test",
	"crates/sweet-cli",
]

[workspace.package]
version = "0.3.0-rc.1"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Peter Hayman <peteyhayman@gmail.com>"]
readme = "README.md"
description = "Delightful Rust testing"
documentation = "https://mrchantey.github.io/forky/docs"
repository = "https://github.com/mrchantey/sweet"
categories = [
	"compilers",
	"development-tools",
	"development-tools::testing",
	"wasm",
	"web-programming",
]
keywords = ["full-stack", "browser", "web", "test", "e2e"]

[workspace.dependencies]
# dont specify version to allow it to be included as a dev dependency but ignored by cargo publish
sweet = { path = "" }
sweet_core = { path = "crates/sweet_core", version = "0.3.0-rc.1" }
sweet_render = { path = "crates/sweet_render", version = "0.3.0-rc.1" }
sweet_rsx = { path = "crates/sweet_rsx", version = "0.3.0-rc.1" }
sweet_rsx_macros = { path = "crates/sweet_rsx/macros", version = "0.3.0-rc.1" }
sweet_server = { path = "crates/sweet_server", version = "0.3.0-rc.1" }
sweet_test = { path = "crates/sweet_test", version = "0.3.0-rc.1" }
sweet_test_macros = { path = "crates/sweet_test/macros", version = "0.3.0-rc.1" }
# forky = { version = "0.2.0-rc.2", path = "../forky/crates/forky" }
# forky = { version = "0.2.1-rc.1", git = "https://github.com/mrchantey/forky" }
# forky = { path = "../forky" }
forky = { version = "0.2.1-rc.1" }


#💡 utility
log = "0.4"
pretty_env_logger = "0.4"
anyhow = "1.0"
thiserror = "2"
backtrace = "0.3.66"
extend = "1.1.2"

#💡 game
bevy = { version = "0.15", default-features = false }

#💡 io ###
clap = { version = "4.2.2", features = ["derive"] }
colorize = "0.1.0"
glob = "0.3.1"

#💡 async
futures = "0.3.28"
futures-util = "0.3.28"
tokio = { version = "1.42", features = [
	"macros",
	"rt",
	"rt-multi-thread",
	"time",
] }
flume = "0.11.1"
# tokio-stream = "0.1.14"
rayon = "1.7.0"

#💡 math
# only cos some dep requires it and we need to enable js feature
getrandom = { version = "0.2", features = ["js"] }

#💡 macros
proc-macro2 = "1"
syn = { version = "2", features = ["full"] }
quote = "1"
rstml = "0.11"
typed-builder = "0.18"

#💡wasm
console_log = "1.0"
js-sys = "0.3.63"
wasm-bindgen = "=0.2.99"
wasm-bindgen-futures = "0.4.36"
console_error_panic_hook = "0.1.7"

#https://rustwasm.github.io/wasm-bindgen/api/web_sys/
#https://github.com/rustwasm/wasm-bindgen/blob/main/crates/web-sys/Cargo.toml
[workspace.dependencies.web-sys]
version = "0.3.76"
features = [
	# Blob
	'Blob',
	'BlobEvent',
	'BlobEventInit',
	'BlobPropertyBag',
	# HTML
	'Headers',
	'Document',
	'Element',
	'Window',
	'HtmlIFrameElement',
	# Style
	'MediaQueryList',
	# Events
	'MouseEvent',
	'KeyboardEvent',
	# JS
	'console',
	'Navigator',
	'Performance',
	# Fetch
	'Request',
	'RequestInit',
	'RequestMode',
	'Response',
	# Blob
	'Blob',
	'BlobEvent',
	'BlobEventInit',
	'BlobPropertyBag',
	# Url
	'Url',
	'History',
	'Location',
	'UrlSearchParams',
	# Sockets
	'BinaryType',
	'FileReader',
	'ErrorEvent',
	'MessageEvent',
	'ProgressEvent',
	'WebSocket',
]


[package]
name = "sweet"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[features]
default = ["server", "rsx", "macros", "render"]

bevy = ["sweet_test?/bevy"]
render = ["dep:sweet_render"]
macros = ["dep:sweet_rsx_macros"]
rsx = ["dep:sweet_rsx"]
server = ["dep:sweet_server"]
test = ["dep:sweet_test"]

[dependencies]
sweet_core.workspace = true
sweet_test = { workspace = true, optional = true }
sweet_render = { workspace = true, optional = true }
sweet_rsx = { workspace = true, optional = true }
sweet_rsx_macros = { workspace = true, optional = true }
sweet_server = { workspace = true, optional = true }


[examples]
counter = { required_features = ["server"] }
render_counter = { required_features = ["server"] }

[dev-dependencies]
sweet_test.workspace = true
sweet_render.workspace = true
sweet_rsx.workspace = true
sweet_rsx_macros.workspace = true
sweet_server.workspace = true
