[workspace]
resolver = "2"              # Important! wgpu/Bevy needs this!
members = ["macros", "cli"]

[workspace.package]
version = "0.3.0-rc.1"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
authors = ["Peter Hayman <peteyhayman@gmail.com>"]
description = "Delightful unified testing in rust"
documentation = "https://mrchantey.github.io/forky/docs"
repository = "https://github.com/mrchantey/sweet"

[workspace.dependencies]
sweet = { path = ".", version = "0.3.0-rc.1" }
sweet_macros = { path = "./macros", version = "0.3.0-rc.1" }
# forky = { version = "0.2.0-rc.2", path = "../forky/crates/forky" }
forky = { path = "../forky" }
# forky = { version = "0.2.0-rc.7" }


#💡 utility
log = "0.4"
pretty_env_logger = "0.4"
anyhow = "1.0"
backtrace = "0.3.66"
extend = "1.1.2"

#💡 game
bevy = { version = "0.15", default-features = false }

#💡 io ###
clap = { version = "4.2.2", features = ["derive"] }
colorize = "0.1.0"
glob = "0.3.1"

#💡 async
futures = "0.3.28"
futures-util = "0.3.28"
tokio = { version = "1.27.0", features = [
	"macros",
	"rt",
	"rt-multi-thread",
	"time",
] }
tokio-stream = "0.1.14"
rayon = "1.7.0"

#💡 math
getrandom = { version = "0.2.9", features = ["js"] }

#💡 macros
proc-macro2 = "1.0.47"
syn = { version = "2.0.*", features = ["full"] }
quote = "1.0.21"
rstml = "0.11.2"
typed-builder = "0.18.0"

#💡wasm
console_log = "1.0"
js-sys = "0.3.63"
wasm-bindgen = "0.2.86"
wasm-bindgen-futures = "0.4.36"
console_error_panic_hook = "0.1.7"

[package]
name = "sweet"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "A very pretty test runner for rust"
documentation = "https://mrchantey.github.io/forky/docs/sweet"
categories = ["development-tools::testing"]
keywords = [ # 5 at most
	"test",
	"unit",
	"e2e",
	"browser",
	"webdriver",
]

[features]
default = ["collect_libtest"]
# allows collecting #[test], requires nightly
collect_libtest = []
bevy = ["dep:bevy"]

[dependencies]
#💡 internal 
forky.workspace = true
sweet_macros.workspace = true

#💡 misc 
anyhow.workspace = true
getrandom.workspace = true
extend.workspace = true

#💡 console 
log.workspace = true
pretty_env_logger.workspace = true
colorize.workspace = true
backtrace.workspace = true

#💡 parse 
glob.workspace = true
clap.workspace = true

#💡 async 
rayon.workspace = true
futures.workspace = true

#💡 bevy 
bevy = { workspace = true, optional = true }


#💡 native
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio.workspace = true
forky = { workspace = true, features = ["fs"] }

#💡 wasm
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log.workspace = true
js-sys.workspace = true
web-sys.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
console_error_panic_hook.workspace = true
forky = { workspace = true, features = ["web"] }


#💡 wasm - dev
[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
[[test]]
name = "test_sweet"
path = "test/sweet.rs"
harness = false
required-features = ["bevy"]


#https://rustwasm.github.io/wasm-bindgen/api/web_sys/
#https://github.com/rustwasm/wasm-bindgen/blob/main/crates/web-sys/Cargo.toml
[workspace.dependencies.web-sys]
version = "0.3.76"
features = [
	# Blob
	'Blob',
	'BlobEvent',
	'BlobEventInit',
	'BlobPropertyBag',
	# HTML
	'Headers',
	'Document',
	'Element',
	'Window',
	'HtmlIFrameElement',
	# Style
	'MediaQueryList',
	# Events
	'MouseEvent',
	'KeyboardEvent',
	# JS
	'console',
	'Navigator',
	'Performance',
	# Fetch
	'Request',
	'RequestInit',
	'RequestMode',
	'Response',
	# Blob
	'Blob',
	'BlobEvent',
	'BlobEventInit',
	'BlobPropertyBag',
	# Url
	'Url',
	'History',
	'Location',
	'UrlSearchParams',
	# Sockets
	'BinaryType',
	'FileReader',
	'ErrorEvent',
	'MessageEvent',
	'ProgressEvent',
	'WebSocket',
]


[[test]]
name = "hello_test"
path = "example_tests/hello_test.rs"

[[test]]
name = "hello_async"
path = "example_tests/hello_async.rs"
[[test]]
name = "sweet_macro"
path = "example_tests/sweet_macro.rs"
