use super::parse_rstml;
use super::RsxFileVisitor;
use super::RsxFileVisitorOut;
use super::WalkNodes;
use proc_macro2::TokenStream;
use sweet_core::tokens::RsxRustTokens;
use syn::visit_mut::VisitMut;
use syn::Expr;
use syn::File;


pub struct RsxParser<T> {
	pub include_errors: bool,
	pub macro_ident: String,
	phantom: std::marker::PhantomData<T>,
}

impl<T> Default for RsxParser<T> {
	fn default() -> Self {
		Self {
			include_errors: true,
			macro_ident: "rsx".to_string(),
			phantom: Default::default(),
		}
	}
}

impl<T: RsxRustTokens> RsxParser<T> {
	/// header to add to the top of each rust file
	pub const SHEBANG: &'static str = "// 🍬 AUTOGENERATED BY SWEET 🍬\n// 🍬 AUTOGENERATED BY SWEET 🍬\n// 🍬 AUTOGENERATED BY SWEET 🍬";

	// entrypoint for file (preprosessor) parsing
	pub fn parse_file(
		&mut self,
		file: &str,
	) -> syn::Result<(File, RsxFileVisitorOut<T>)> {
		// errors in preprocessed files are not included, rstml
		// gets confused
		self.include_errors = false;
		let mut file = syn::parse_file(file)?;
		let mut visitor = RsxFileVisitor::new(self);
		visitor.visit_file_mut(&mut file);
		// Validate space
		file.shebang = Some(Self::SHEBANG.to_string());
		Ok((file, visitor.into()))
	}


	/// entrypoint for inline (macro) parsing.
	/// Called when visiting an rsx macro.
	/// Mutated in place for efficient file parsing
	pub fn parse_rsx(&mut self, tokens: &mut TokenStream) -> WalkNodes<T> {
		let (nodes, rstml_errors) = parse_rstml(tokens.clone());
		let mut output = WalkNodes::default();
		let nodes = output.map_nodes(nodes);

		let WalkNodes {
			errors,
			collected_elements,
			..
		} = &output;

		let _ = collected_elements;

		let errors = if self.include_errors {
			let errs = rstml_errors
				.into_iter()
				.map(|e| e.emit_as_expr_tokens())
				.chain(errors.clone());
			quote::quote! {#(#errs;)*}
		} else {
			Default::default()
		};

		let ident = T::ident();
		*tokens = syn::parse_quote! {{
			use sweet::prelude::*;
			#errors

			#[allow(unused_braces)]
			{
				RsxTree {
					nodes: Vec::from([#(#nodes),*]),
				} as RsxTree::<#ident>
			}
		}};
		output
	}

	/// Check if a path matches the macro, by default only the last segment is checked
	pub fn path_matches(&self, path: &syn::Path) -> bool {
		path.segments
			.last()
			.map_or(false, |seg| seg.ident == self.macro_ident)
	}
}

pub fn macro_or_err(expr: &Expr) -> syn::Result<&syn::Macro> {
	if let Expr::Macro(mac) = expr {
		Ok(&mac.mac)
	} else {
		Err(syn::Error::new_spanned(expr, "expected macro"))
	}
}
#[cfg(test)]
mod test {
	use sweet_core as sweet;
	use sweet_rsx_macros::rsx;
	use sweet_test::prelude::*;

	#[test]
	fn compiles() {
		let onclick = |_: u32| {};
		let world = "mars";
		let _rsx = rsx! {
			<div onclick>
				<p>hello {world}</p>
			</div>
		};
	}
	#[test]
	fn compiles2() {
		let parts = rsx! {<div> the value is {3} </div>};

		expect(parts.build_string()).to_be("<div> the value is 3</div>");
	}
}
