use super::parse_rstml;
use super::RsxFileVisitor;
use super::RsxFileVisitorOut;
use super::WalkNodesOutput;
use proc_macro2::TokenStream;
use sweet_core::rsx::RsxTree;
use syn::visit_mut::VisitMut;
use syn::Expr;
use syn::File;


pub struct RsxParser {
	pub include_errors: bool,
	pub macro_ident: String,
}

impl Default for RsxParser {
	fn default() -> Self {
		Self {
			include_errors: true,
			macro_ident: "rsx".to_string(),
		}
	}
}

impl RsxParser {
	/// header to add to the top of each rust file
	pub const SHEBANG: &'static str = "// 🍬 AUTOGENERATED BY SWEET 🍬\n// 🍬 AUTOGENERATED BY SWEET 🍬\n// 🍬 AUTOGENERATED BY SWEET 🍬";

	// entrypoint for file (preprosessor) parsing
	pub fn parse_file(
		&mut self,
		file: &str,
	) -> syn::Result<(File, RsxFileVisitorOut)> {
		// errors in preprocessed files are not included, rstml
		// gets confused
		self.include_errors = false;
		let mut file = syn::parse_file(file)?;
		let mut visitor = RsxFileVisitor::new(self);
		visitor.visit_file_mut(&mut file);
		// Validate space
		file.shebang = Some(Self::SHEBANG.to_string());
		Ok((file, visitor.into()))
	}


	/// entrypoint for inline (macro) parsing.
	/// Called when visiting an rsx macro.
	/// Mutated in place for efficient file parsing
	pub fn parse_rsx(
		&mut self,
		tokens: &mut TokenStream,
	) -> syn::Result<WalkNodesOutput> {
		let (nodes, rstml_errors) = parse_rstml(tokens.clone());
		let mut output = WalkNodesOutput::default();
		let nodes = output.visit_nodes(nodes);
		let tree = RsxTree::new(nodes);

		let WalkNodesOutput {
			errors,
			collected_elements,
			..
		} = output.clone();

		let _ = collected_elements;

		let errors = if self.include_errors {
			let errs = rstml_errors
				.into_iter()
				.map(|e| e.emit_as_expr_tokens())
				.chain(errors);
			quote::quote! {#(#errs;)*}
		} else {
			Default::default()
		};

		*tokens = syn::parse_quote! {{
			use sweet::prelude::*;
			#errors
			#tree as RsxTree::<RustParts>
		}};
		Ok(output)
	}

	/// Check if a path matches the macro, by default only the last segment is checked
	pub fn path_matches(&self, path: &syn::Path) -> bool {
		path.segments
			.last()
			.map_or(false, |seg| seg.ident == self.macro_ident)
	}
}

pub fn macro_or_err(expr: &Expr) -> syn::Result<&syn::Macro> {
	if let Expr::Macro(mac) = expr {
		Ok(&mac.mac)
	} else {
		Err(syn::Error::new_spanned(expr, "expected macro"))
	}
}
#[cfg(test)]
mod test {
	use sweet_core as sweet;
	use sweet_rsx_macros::rsx;
	use sweet_test::prelude::*;

	#[test]
	fn compiles() {
		let onclick = |_| {};
		let world = "mars";
		let _rsx = rsx! {
			<div onclick>
				<p>hello {world}</p>
			</div>
		};
	}
	#[test]
	fn compiles2() {
		let parts = rsx! {<div> the value is {3} </div>};
		let parts_str = format!("{:?}", parts);

		expect(parts_str).to_be("RsxTree { nodes: [Element(Element { tag: \"div\", attributes: [], children: [Text(\" the value is \"), TextBlock(TextBlock)], self_closing: false })] }");
	}
}
