# Using the sweet wasm runner:
# 1. `cargo binstall sweet-cli`
# 2. add the following to .cargo/config.toml:

# 	[target.wasm32-unknown-unknown]
# 	runner = 'sweet test-wasm'
# 	[env]
# 	SWEET_ROOT = { value = "", relative = true }

[target.wasm32-unknown-unknown]
runner = 'cargo run -p sweet-cli -- test-wasm'


[env]
SWEET_ROOT = { value = "", relative = true }
