[build]
jobs = 8

[target.wasm32-unknown-unknown]
runner = 'cargo run -p sweet-cli -- test-wasm'
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]

[env]
SWEET_ROOT = { value = "", relative = true }
