[package]
name = "sweet_rsx"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true


[dependencies]
thiserror.workspace = true
anyhow.workspace = true
sweet_rsx_macros.workspace = true
forky = { workspace = true, features = ["fs"] }
