[package]
name = "sweet_rsx"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true


[dependencies]
sweet_rsx_macros.workspace = true